### ISSUE TITLE
Guide Code Complete Master Tracking Issue

### ISSUE THREAD

**Issue by avive** [spacemeshos/testnet-guide#7]
Summary of high-level task for finalizing the guide:
- [x] Proof-read all pages
- [x] Test all links
- [x] Update all screen shots with final app screen shots which include the UI fixes from the recent UI reviews
- [x] Record, upload to youtube and include each text guide the video version of each of the guides
- [x] Finalize instructions for non-complete features (e.g. auto update, sending coin, viewing incoming TXs, viewing awards)

@liathoffman
